#ifndef COLORS_H
#define COLORS_H

#pragma once

namespace Colors
{
    const unsigned char VIOLET = 0x1;
    const unsigned char MAGENTA = 0x2;
    const unsigned char PINK = 0x3;
    const unsigned char WHITE = 0x4;
    const unsigned char CYAN = 0x5;
    const unsigned char BLUE_LIGHT = 0x6;
    const unsigned char BLUE_DARK = 0x7;
    const unsigned char PURPLE_DARK = 0x8;
    const unsigned char BLACK = 0x9;
    const unsigned char GREEN_LIME = 0xA;
    const unsigned char YELLOW = 0xB;
    const unsigned char ORANGE = 0xC;
    const unsigned char RED_DARK = 0xD;
    const unsigned char RED_BROWN = 0xE;
    const unsigned char BROWN = 0xF;
    const unsigned char BEIGE_LIGHT = 0x10;
};

#endif // COLORS_H